pre_prompt_b = "I am giving you a list of items in my basket below and I want you to generate a meal for me using the items from the basket make sure to use most of the items and create a name for the dish and I will be giving you different items for breakfast in the basket and you need to generate a meal and the name of the meal by using all the items in each category that is breakfast, lunch, and dinner so this is the list for items for the breakfast meal: "

pre_prompt_l = "I am giving you a list of items in my basket below and I want you to generate a meal for me using the items from the basket make sure to use most of the items and create a name for the dish and I will be giving you different items for lunch in the basket and you need to generate a meal and the name of the meal by using all the items in each category that is breakfast, lunch, and dinner so this is the list for items for the lunch meal: "

pre_prompt_d = "I am giving you a list of items in my basket below and I want you to generate a meal for me using the items from the basket make sure to use most of the items and create a name for the dish and I will be giving you different items for dinner in the basket and you need to generate a meal and the name of the meal by using all the items in each category that is breakfast, lunch, and dinner so this is the list for items for the dinner meal: "

pre_breakfast = "For breakfast, we have a scrumptious dish called 'Sunrise Scramble'. It features fluffy scrambled eggs infused with earthy mushrooms and colorful bell peppers. This combination is guaranteed to kickstart your day with a burst of flavor and energy. This is just an example you can use your own creativity to generate based on the list provided."

pre_lunch = "Here the example but use your own creativity to generate based on the list provided : For lunch, we have a refreshing creation known as 'Tropical Yogurt Delight.' This mouthwatering salad combines creamy Greek yogurt with tangy oranges and crunchy nuts. Each bite will transport you to a tropical paradise, filling you with satisfaction and nourishment. This is just an example you can use your own creativity to generate based on the list provided. "

pre_dinner = "Here the example but use your own creativity to generate based on the list provided : Now, for the grand finale, let's dive into a dinner masterpiece called 'Stuffed Spinach Sensation.' Here, we take tender chicken breasts and fill them to the brim with a vibrant mixture of spinach and juicy tomatoes. The result is a tantalizing dish that will leave you craving more. This is just an example you can use your own creativity to generate based on the list provided."

end_text = "Remember, hydration is key to staying refreshed and energized throughout the day. So, keep a glass of water handy and sip it to your heart's content. Get ready to savor this extraordinary culinary experience and let your taste buds dance with joy. Enjoy your meals and have a fantastic day!"

example_response_l = f"This is just an example but use your creativity: You can start with, I'm thrilled to be your Lunch planner, and I've crafted a delightful and flavorful meal plan just for you. But fear not, this isn't your ordinary, run-of-the-mill meal plan. It's a culinary adventure designed to keep your taste buds excited while considering the calories you can intake."

example_response_d = f"This is just an example but use your creativity: You can start with, I'm thrilled to be your dinner, and I've crafted a delightful and flavorful meal plan just for you. But fear not, this isn't your ordinary, run-of-the-mill meal plan. It's a culinary adventure designed to keep your taste buds excited while considering the calories you can intake."

negative_prompt = "Do not include instruction to prepare the meal. I want only the name of the meal and the ingredients used in the meal and explaining the dish you suggested and spill some nutritious knowledge. You your master chef cooking skills to generate the meals. You can be as precise as possible."
